version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fe_wiki
      POSTGRES_USER: fe_wiki
      POSTGRES_PASSWORD: fe_wiki_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./demo:/usr/share/nginx/html

volumes:
  postgres_data: